import type {
  Broker,
  PortfolioView,
  PortfolioSummary,
  AssetClassSummary,
  PortfolioHolding,
  AccountPosition,
  TaxLot,
  AllocationSegment,
  BentoCardConfig,
} from '../types/portfolio'

// Broker definitions
export const brokers: Broker[] = [
  {
    id: 'ibkr',
    name: 'Interactive Brokers',
    shortName: 'IB',
    region: 'US',
    supportedAssets: ['equities', 'fx', 'fixed-income', 'metals'],
    iconColor: 'linear-gradient(135deg, #d32f2f, #b71c1c)',
  },
  {
    id: 'degiro',
    name: 'Degiro',
    shortName: 'DG',
    region: 'EU',
    supportedAssets: ['equities'],
    iconColor: 'linear-gradient(135deg, #0288d1, #01579b)',
  },
  {
    id: 'saxo',
    name: 'Saxo Bank',
    shortName: 'SX',
    region: 'EU',
    supportedAssets: ['equities', 'fx', 'fixed-income'],
    iconColor: 'linear-gradient(135deg, #1565c0, #0d47a1)',
  },
  {
    id: 'oanda',
    name: 'OANDA',
    shortName: 'OA',
    region: 'Global',
    supportedAssets: ['fx'],
    iconColor: 'linear-gradient(135deg, #2e7d32, #1b5e20)',
  },
  {
    id: 'coinbase',
    name: 'Coinbase',
    shortName: 'CB',
    region: 'US',
    supportedAssets: ['crypto'],
    iconColor: 'linear-gradient(135deg, #1652f0, #0d3ac4)',
  },
  {
    id: 'kraken',
    name: 'Kraken',
    shortName: 'KR',
    region: 'US',
    supportedAssets: ['crypto'],
    iconColor: 'linear-gradient(135deg, #5741d9, #3d2ba8)',
  },
  {
    id: 'bullionvault',
    name: 'BullionVault',
    shortName: 'BV',
    region: 'UK',
    supportedAssets: ['metals'],
    iconColor: 'linear-gradient(135deg, #f59e0b, #d97706)',
  },
  {
    id: 'polymarket',
    name: 'Polymarket',
    shortName: 'PM',
    region: 'Global',
    supportedAssets: ['prediction-markets'],
    iconColor: 'linear-gradient(135deg, #0891b2, #0e7490)',
  },
  {
    id: 'kalshi',
    name: 'Kalshi',
    shortName: 'KA',
    region: 'US',
    supportedAssets: ['prediction-markets'],
    iconColor: 'linear-gradient(135deg, #7c3aed, #5b21b6)',
  },
]

// Helper to get broker by ID
export const getBrokerById = (id: string): Broker | undefined =>
  brokers.find((b) => b.id === id)

// Portfolio Views
export const portfolioViews: PortfolioView[] = [
  {
    id: 'all-assets',
    name: 'All Assets',
    isDefault: true,
    filters: {},
  },
  {
    id: 'us-equities',
    name: 'US Equities',
    filters: {
      assetClasses: ['equities'],
      regions: ['US'],
    },
  },
  {
    id: 'eu-portfolio',
    name: 'EU Portfolio',
    filters: {
      regions: ['EU'],
    },
  },
]

// Tax lots for NVDA at Interactive Brokers
const nvdaIBKRTaxLots: TaxLot[] = [
  {
    id: 'nvda-lot-1',
    purchaseDate: '2023-03-15',
    shares: 50,
    costBasis: 245.0,
    currentValue: 43764.0,
    gainLoss: 31514.0,
    gainLossPercent: 257.69,
    isLongTerm: true,
    estimatedTax: 4727.1,
    taxRate: 0.15,
  },
  {
    id: 'nvda-lot-2',
    purchaseDate: '2023-07-22',
    shares: 60,
    costBasis: 285.5,
    currentValue: 52516.8,
    gainLoss: 35386.8,
    gainLossPercent: 206.54,
    isLongTerm: true,
    estimatedTax: 5308.02,
    taxRate: 0.15,
  },
  {
    id: 'nvda-lot-3',
    purchaseDate: '2024-10-10',
    shares: 40,
    costBasis: 340.0,
    currentValue: 35011.2,
    gainLoss: 21411.2,
    gainLossPercent: 157.44,
    isLongTerm: false,
    daysToLongTerm: 265,
    estimatedTax: 7493.92,
    taxRate: 0.35,
  },
]

// Tax lots for NVDA at Degiro
const nvdaDegiroTaxLots: TaxLot[] = [
  {
    id: 'nvda-dg-lot-1',
    purchaseDate: '2023-09-05',
    shares: 30,
    costBasis: 310.5,
    currentValue: 26258.4,
    gainLoss: 16943.4,
    gainLossPercent: 182.04,
    isLongTerm: true,
    estimatedTax: 2541.51,
    taxRate: 0.15,
  },
  {
    id: 'nvda-dg-lot-2',
    purchaseDate: '2024-11-20',
    shares: 20,
    costBasis: 145.0,
    currentValue: 17505.6,
    gainLoss: 14605.6,
    gainLossPercent: 503.64,
    isLongTerm: false,
    daysToLongTerm: 306,
    estimatedTax: 5111.96,
    taxRate: 0.35,
  },
]

// NVDA account positions
const nvdaAccounts: AccountPosition[] = [
  {
    accountId: 'ibkr-margin-1',
    brokerId: 'ibkr',
    brokerName: 'Interactive Brokers',
    brokerShortName: 'IB',
    accountType: 'Margin',
    region: 'US',
    shares: 150,
    averageCost: 285.0,
    currentValue: 131292.0,
    costBasis: 42750.0,
    gainLoss: 88542.0,
    gainLossPercent: 207.12,
    taxLots: nvdaIBKRTaxLots,
    washSaleWarnings: [
      {
        symbol: 'NVDA',
        saleDate: '2025-01-05',
        sharesAmount: 20,
        lossAmount: 1250.0,
        windowEndDate: '2025-02-04',
      },
    ],
  },
  {
    accountId: 'degiro-cash-1',
    brokerId: 'degiro',
    brokerName: 'Degiro',
    brokerShortName: 'DG',
    accountType: 'Cash',
    region: 'EU',
    shares: 50,
    averageCost: 310.5,
    currentValue: 43764.0,
    costBasis: 15525.0,
    gainLoss: 28239.0,
    gainLossPercent: 181.87,
    taxLots: nvdaDegiroTaxLots,
  },
]

// MSFT account positions
const msftAccounts: AccountPosition[] = [
  {
    accountId: 'ibkr-margin-1',
    brokerId: 'ibkr',
    brokerName: 'Interactive Brokers',
    brokerShortName: 'IB',
    accountType: 'Margin',
    region: 'US',
    shares: 200,
    averageCost: 298.45,
    currentValue: 83134.0,
    costBasis: 59690.0,
    gainLoss: 23444.0,
    gainLossPercent: 39.28,
    taxLots: [
      {
        id: 'msft-lot-1',
        purchaseDate: '2022-11-15',
        shares: 200,
        costBasis: 298.45,
        currentValue: 83134.0,
        gainLoss: 23444.0,
        gainLossPercent: 39.28,
        isLongTerm: true,
        estimatedTax: 3516.6,
        taxRate: 0.15,
      },
    ],
  },
  {
    accountId: 'saxo-cash-1',
    brokerId: 'saxo',
    brokerName: 'Saxo Bank',
    brokerShortName: 'SX',
    accountType: 'Cash',
    region: 'EU',
    shares: 120,
    averageCost: 305.2,
    currentValue: 49880.4,
    costBasis: 36624.0,
    gainLoss: 13256.4,
    gainLossPercent: 36.2,
    taxLots: [
      {
        id: 'msft-saxo-lot-1',
        purchaseDate: '2023-02-10',
        shares: 120,
        costBasis: 305.2,
        currentValue: 49880.4,
        gainLoss: 13256.4,
        gainLossPercent: 36.2,
        isLongTerm: true,
        estimatedTax: 1988.46,
        taxRate: 0.15,
      },
    ],
  },
]

// Equity holdings
const equityHoldings: PortfolioHolding[] = [
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corp.',
    assetClass: 'equities',
    totalShares: 200,
    totalValue: 175056.0,
    dayChange: 4876.5,
    dayChangePercent: 2.87,
    totalGainLoss: 116781.0,
    totalGainLossPercent: 200.01,
    accounts: nvdaAccounts,
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corp.',
    assetClass: 'equities',
    totalShares: 320,
    totalValue: 133014.4,
    dayChange: -987.2,
    dayChangePercent: -0.74,
    totalGainLoss: 36700.4,
    totalGainLossPercent: 38.1,
    accounts: msftAccounts,
  },
  {
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    assetClass: 'equities',
    totalShares: 400,
    totalValue: 99500.0,
    dayChange: -2400.0,
    dayChangePercent: -2.35,
    totalGainLoss: 20100.0,
    totalGainLossPercent: 25.31,
    accounts: [
      {
        accountId: 'ibkr-margin-1',
        brokerId: 'ibkr',
        brokerName: 'Interactive Brokers',
        brokerShortName: 'IB',
        accountType: 'Margin',
        region: 'US',
        shares: 400,
        averageCost: 198.5,
        currentValue: 99500.0,
        costBasis: 79400.0,
        gainLoss: 20100.0,
        gainLossPercent: 25.31,
        taxLots: [
          {
            id: 'tsla-lot-1',
            purchaseDate: '2024-02-15',
            shares: 400,
            costBasis: 198.5,
            currentValue: 99500.0,
            gainLoss: 20100.0,
            gainLossPercent: 25.31,
            isLongTerm: false,
            daysToLongTerm: 27,
            estimatedTax: 7035.0,
            taxRate: 0.35,
          },
        ],
      },
    ],
  },
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    assetClass: 'equities',
    totalShares: 450,
    totalValue: 80244.0,
    dayChange: 1245.6,
    dayChangePercent: 1.58,
    totalGainLoss: 16119.0,
    totalGainLossPercent: 25.14,
    accounts: [
      {
        accountId: 'ibkr-margin-1',
        brokerId: 'ibkr',
        brokerName: 'Interactive Brokers',
        brokerShortName: 'IB',
        accountType: 'Margin',
        region: 'US',
        shares: 300,
        averageCost: 142.5,
        currentValue: 53496.0,
        costBasis: 42750.0,
        gainLoss: 10746.0,
        gainLossPercent: 25.14,
        taxLots: [
          {
            id: 'aapl-lot-1',
            purchaseDate: '2022-06-20',
            shares: 300,
            costBasis: 142.5,
            currentValue: 53496.0,
            gainLoss: 10746.0,
            gainLossPercent: 25.14,
            isLongTerm: true,
            estimatedTax: 1611.9,
            taxRate: 0.15,
          },
        ],
      },
      {
        accountId: 'degiro-cash-1',
        brokerId: 'degiro',
        brokerName: 'Degiro',
        brokerShortName: 'DG',
        accountType: 'Cash',
        region: 'EU',
        shares: 150,
        averageCost: 145.0,
        currentValue: 26748.0,
        costBasis: 21750.0,
        gainLoss: 4998.0,
        gainLossPercent: 22.98,
        taxLots: [
          {
            id: 'aapl-dg-lot-1',
            purchaseDate: '2023-01-10',
            shares: 150,
            costBasis: 145.0,
            currentValue: 26748.0,
            gainLoss: 4998.0,
            gainLossPercent: 22.98,
            isLongTerm: true,
            estimatedTax: 749.7,
            taxRate: 0.15,
          },
        ],
      },
    ],
  },
  {
    symbol: 'META',
    name: 'Meta Platforms',
    assetClass: 'equities',
    totalShares: 150,
    totalValue: 75798.0,
    dayChange: 1234.5,
    dayChangePercent: 1.66,
    totalGainLoss: 30985.5,
    totalGainLossPercent: 69.16,
    accounts: [
      {
        accountId: 'ibkr-margin-1',
        brokerId: 'ibkr',
        brokerName: 'Interactive Brokers',
        brokerShortName: 'IB',
        accountType: 'Margin',
        region: 'US',
        shares: 150,
        averageCost: 298.75,
        currentValue: 75798.0,
        costBasis: 44812.5,
        gainLoss: 30985.5,
        gainLossPercent: 69.16,
        taxLots: [
          {
            id: 'meta-lot-1',
            purchaseDate: '2023-05-15',
            shares: 150,
            costBasis: 298.75,
            currentValue: 75798.0,
            gainLoss: 30985.5,
            gainLossPercent: 69.16,
            isLongTerm: true,
            estimatedTax: 4647.83,
            taxRate: 0.15,
          },
        ],
      },
    ],
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    assetClass: 'equities',
    totalShares: 180,
    totalValue: 31575.6,
    dayChange: 432.0,
    dayChangePercent: 1.39,
    totalGainLoss: 8931.6,
    totalGainLossPercent: 39.45,
    accounts: [
      {
        accountId: 'saxo-cash-1',
        brokerId: 'saxo',
        brokerName: 'Saxo Bank',
        brokerShortName: 'SX',
        accountType: 'Cash',
        region: 'EU',
        shares: 180,
        averageCost: 125.8,
        currentValue: 31575.6,
        costBasis: 22644.0,
        gainLoss: 8931.6,
        gainLossPercent: 39.45,
        taxLots: [
          {
            id: 'googl-lot-1',
            purchaseDate: '2023-03-20',
            shares: 180,
            costBasis: 125.8,
            currentValue: 31575.6,
            gainLoss: 8931.6,
            gainLossPercent: 39.45,
            isLongTerm: true,
            estimatedTax: 1339.74,
            taxRate: 0.15,
          },
        ],
      },
    ],
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    assetClass: 'equities',
    totalShares: 280,
    totalValue: 52066.0,
    dayChange: 784.0,
    dayChangePercent: 1.53,
    totalGainLoss: 12222.0,
    totalGainLossPercent: 30.68,
    accounts: [
      {
        accountId: 'ibkr-margin-1',
        brokerId: 'ibkr',
        brokerName: 'Interactive Brokers',
        brokerShortName: 'IB',
        accountType: 'Margin',
        region: 'US',
        shares: 280,
        averageCost: 142.3,
        currentValue: 52066.0,
        costBasis: 39844.0,
        gainLoss: 12222.0,
        gainLossPercent: 30.68,
        taxLots: [
          {
            id: 'amzn-lot-1',
            purchaseDate: '2023-04-10',
            shares: 280,
            costBasis: 142.3,
            currentValue: 52066.0,
            gainLoss: 12222.0,
            gainLossPercent: 30.68,
            isLongTerm: true,
            estimatedTax: 1833.3,
            taxRate: 0.15,
          },
        ],
      },
    ],
  },
  {
    symbol: 'JPM',
    name: 'JPMorgan Chase',
    assetClass: 'equities',
    totalShares: 350,
    totalValue: 69450.5,
    dayChange: 875.0,
    dayChangePercent: 1.27,
    totalGainLoss: 18630.5,
    totalGainLossPercent: 36.66,
    accounts: [
      {
        accountId: 'ibkr-margin-1',
        brokerId: 'ibkr',
        brokerName: 'Interactive Brokers',
        brokerShortName: 'IB',
        accountType: 'Margin',
        region: 'US',
        shares: 350,
        averageCost: 145.2,
        currentValue: 69450.5,
        costBasis: 50820.0,
        gainLoss: 18630.5,
        gainLossPercent: 36.66,
        taxLots: [
          {
            id: 'jpm-lot-1',
            purchaseDate: '2022-09-15',
            shares: 350,
            costBasis: 145.2,
            currentValue: 69450.5,
            gainLoss: 18630.5,
            gainLossPercent: 36.66,
            isLongTerm: true,
            estimatedTax: 2794.58,
            taxRate: 0.15,
          },
        ],
      },
    ],
  },
]

// Crypto holdings
const cryptoHoldings: PortfolioHolding[] = [
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    assetClass: 'crypto',
    totalShares: 2.0,
    totalValue: 134865.0,
    dayChange: 4315.68,
    dayChangePercent: 3.2,
    totalGainLoss: 42015.0,
    totalGainLossPercent: 45.24,
    accounts: [
      {
        accountId: 'coinbase-vault-1',
        brokerId: 'coinbase',
        brokerName: 'Coinbase',
        brokerShortName: 'CB',
        accountType: 'Vault',
        region: 'US',
        shares: 1.5,
        averageCost: 42500.0,
        currentValue: 101148.75,
        costBasis: 63750.0,
        gainLoss: 37398.75,
        gainLossPercent: 58.66,
        taxLots: [
          {
            id: 'btc-cb-lot-1',
            purchaseDate: '2023-01-15',
            shares: 1.5,
            costBasis: 42500.0,
            currentValue: 101148.75,
            gainLoss: 37398.75,
            gainLossPercent: 58.66,
            isLongTerm: true,
            estimatedTax: 5609.81,
            taxRate: 0.15,
          },
        ],
      },
      {
        accountId: 'kraken-trading-1',
        brokerId: 'kraken',
        brokerName: 'Kraken',
        brokerShortName: 'KR',
        accountType: 'Trading',
        region: 'US',
        shares: 0.5,
        averageCost: 58200.0,
        currentValue: 33716.25,
        costBasis: 29100.0,
        gainLoss: 4616.25,
        gainLossPercent: 15.86,
        taxLots: [
          {
            id: 'btc-kr-lot-1',
            purchaseDate: '2024-08-20',
            shares: 0.5,
            costBasis: 58200.0,
            currentValue: 33716.25,
            gainLoss: 4616.25,
            gainLossPercent: 15.86,
            isLongTerm: false,
            daysToLongTerm: 213,
            estimatedTax: 1615.69,
            taxRate: 0.35,
          },
        ],
      },
    ],
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    assetClass: 'crypto',
    totalShares: 25.0,
    totalValue: 62450.0,
    dayChange: 3184.95,
    dayChangePercent: 5.1,
    totalGainLoss: 18450.0,
    totalGainLossPercent: 41.93,
    accounts: [
      {
        accountId: 'coinbase-vault-1',
        brokerId: 'coinbase',
        brokerName: 'Coinbase',
        brokerShortName: 'CB',
        accountType: 'Vault',
        region: 'US',
        shares: 25.0,
        averageCost: 1760.0,
        currentValue: 62450.0,
        costBasis: 44000.0,
        gainLoss: 18450.0,
        gainLossPercent: 41.93,
        taxLots: [
          {
            id: 'eth-lot-1',
            purchaseDate: '2023-06-10',
            shares: 25.0,
            costBasis: 1760.0,
            currentValue: 62450.0,
            gainLoss: 18450.0,
            gainLossPercent: 41.93,
            isLongTerm: true,
            estimatedTax: 2767.5,
            taxRate: 0.15,
          },
        ],
      },
    ],
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    assetClass: 'crypto',
    totalShares: 300.0,
    totalValue: 30495.6,
    dayChange: 2561.63,
    dayChangePercent: 8.4,
    totalGainLoss: 12495.6,
    totalGainLossPercent: 69.42,
    accounts: [
      {
        accountId: 'kraken-trading-1',
        brokerId: 'kraken',
        brokerName: 'Kraken',
        brokerShortName: 'KR',
        accountType: 'Trading',
        region: 'US',
        shares: 300.0,
        averageCost: 60.0,
        currentValue: 30495.6,
        costBasis: 18000.0,
        gainLoss: 12495.6,
        gainLossPercent: 69.42,
        taxLots: [
          {
            id: 'sol-lot-1',
            purchaseDate: '2024-03-15',
            shares: 300.0,
            costBasis: 60.0,
            currentValue: 30495.6,
            gainLoss: 12495.6,
            gainLossPercent: 69.42,
            isLongTerm: false,
            daysToLongTerm: 55,
            estimatedTax: 4373.46,
            taxRate: 0.35,
          },
        ],
      },
    ],
  },
]

// FX holdings
const fxHoldings: PortfolioHolding[] = [
  {
    symbol: 'EUR/USD',
    name: 'Euro / US Dollar',
    assetClass: 'fx',
    totalShares: 150000,
    totalValue: 162750.0,
    dayChange: 1627.5,
    dayChangePercent: 1.01,
    totalGainLoss: 7500.0,
    totalGainLossPercent: 4.83,
    accounts: [
      {
        accountId: 'oanda-trading-1',
        brokerId: 'oanda',
        brokerName: 'OANDA',
        brokerShortName: 'OA',
        accountType: 'Trading',
        region: 'Global',
        shares: 150000,
        averageCost: 1.035,
        currentValue: 162750.0,
        costBasis: 155250.0,
        gainLoss: 7500.0,
        gainLossPercent: 4.83,
        taxLots: [],
      },
    ],
  },
  {
    symbol: 'GBP/USD',
    name: 'British Pound / US Dollar',
    assetClass: 'fx',
    totalShares: 80000,
    totalValue: 101600.0,
    dayChange: 2032.0,
    dayChangePercent: 2.04,
    totalGainLoss: 4800.0,
    totalGainLossPercent: 4.96,
    accounts: [
      {
        accountId: 'oanda-trading-1',
        brokerId: 'oanda',
        brokerName: 'OANDA',
        brokerShortName: 'OA',
        accountType: 'Trading',
        region: 'Global',
        shares: 80000,
        averageCost: 1.21,
        currentValue: 101600.0,
        costBasis: 96800.0,
        gainLoss: 4800.0,
        gainLossPercent: 4.96,
        taxLots: [],
      },
    ],
  },
  {
    symbol: 'USD/JPY',
    name: 'US Dollar / Japanese Yen',
    assetClass: 'fx',
    totalShares: 50000,
    totalValue: 47365.89,
    dayChange: 710.49,
    dayChangePercent: 1.52,
    totalGainLoss: 2365.89,
    totalGainLossPercent: 5.26,
    accounts: [
      {
        accountId: 'oanda-trading-1',
        brokerId: 'oanda',
        brokerName: 'OANDA',
        brokerShortName: 'OA',
        accountType: 'Trading',
        region: 'Global',
        shares: 50000,
        averageCost: 0.9,
        currentValue: 47365.89,
        costBasis: 45000.0,
        gainLoss: 2365.89,
        gainLossPercent: 5.26,
        taxLots: [],
      },
    ],
  },
  {
    symbol: 'AUD/USD',
    name: 'Australian Dollar / US Dollar',
    assetClass: 'fx',
    totalShares: 45000,
    totalValue: 30000.0,
    dayChange: 462.11,
    dayChangePercent: 1.56,
    totalGainLoss: 1800.0,
    totalGainLossPercent: 6.38,
    accounts: [
      {
        accountId: 'oanda-trading-1',
        brokerId: 'oanda',
        brokerName: 'OANDA',
        brokerShortName: 'OA',
        accountType: 'Trading',
        region: 'Global',
        shares: 45000,
        averageCost: 0.627,
        currentValue: 30000.0,
        costBasis: 28200.0,
        gainLoss: 1800.0,
        gainLossPercent: 6.38,
        taxLots: [],
      },
    ],
  },
]

// Fixed Income holdings
const fixedIncomeHoldings: PortfolioHolding[] = [
  {
    symbol: 'US10Y',
    name: 'US Treasury 10Y Bond',
    assetClass: 'fixed-income',
    totalShares: 100,
    totalValue: 198450.0,
    dayChange: 396.9,
    dayChangePercent: 0.2,
    totalGainLoss: 3450.0,
    totalGainLossPercent: 1.77,
    accounts: [
      {
        accountId: 'ibkr-margin-1',
        brokerId: 'ibkr',
        brokerName: 'Interactive Brokers',
        brokerShortName: 'IB',
        accountType: 'Margin',
        region: 'US',
        shares: 100,
        averageCost: 1950.0,
        currentValue: 198450.0,
        costBasis: 195000.0,
        gainLoss: 3450.0,
        gainLossPercent: 1.77,
        taxLots: [],
      },
    ],
  },
  {
    symbol: 'CORP-AAA',
    name: 'Corporate Bond AAA ETF',
    assetClass: 'fixed-income',
    totalShares: 200,
    totalValue: 156573.84,
    dayChange: 469.72,
    dayChangePercent: 0.3,
    totalGainLoss: 4573.84,
    totalGainLossPercent: 3.01,
    accounts: [
      {
        accountId: 'saxo-cash-1',
        brokerId: 'saxo',
        brokerName: 'Saxo Bank',
        brokerShortName: 'SX',
        accountType: 'Cash',
        region: 'EU',
        shares: 200,
        averageCost: 760.0,
        currentValue: 156573.84,
        costBasis: 152000.0,
        gainLoss: 4573.84,
        gainLossPercent: 3.01,
        taxLots: [],
      },
    ],
  },
  {
    symbol: 'MUNI-CA',
    name: 'California Municipal Bond',
    assetClass: 'fixed-income',
    totalShares: 150,
    totalValue: 157550.0,
    dayChange: 378.58,
    dayChangePercent: 0.24,
    totalGainLoss: 2550.0,
    totalGainLossPercent: 1.65,
    accounts: [
      {
        accountId: 'ibkr-margin-1',
        brokerId: 'ibkr',
        brokerName: 'Interactive Brokers',
        brokerShortName: 'IB',
        accountType: 'Margin',
        region: 'US',
        shares: 150,
        averageCost: 1033.33,
        currentValue: 157550.0,
        costBasis: 155000.0,
        gainLoss: 2550.0,
        gainLossPercent: 1.65,
        taxLots: [],
      },
    ],
  },
]

// Metals holdings
const metalsHoldings: PortfolioHolding[] = [
  {
    symbol: 'XAU',
    name: 'Gold',
    assetClass: 'metals',
    totalShares: 5.2,
    totalValue: 245000.0,
    dayChange: 1764.0,
    dayChangePercent: 0.72,
    totalGainLoss: 15600.0,
    totalGainLossPercent: 6.8,
    accounts: [
      {
        accountId: 'bullionvault-1',
        brokerId: 'bullionvault',
        brokerName: 'BullionVault',
        brokerShortName: 'BV',
        accountType: 'Vault',
        region: 'UK',
        shares: 5.2,
        averageCost: 44115.38,
        currentValue: 245000.0,
        costBasis: 229400.0,
        gainLoss: 15600.0,
        gainLossPercent: 6.8,
        taxLots: [],
      },
    ],
  },
  {
    symbol: 'XAG',
    name: 'Silver',
    assetClass: 'metals',
    totalShares: 180,
    totalValue: 65000.0,
    dayChange: 292.5,
    dayChangePercent: 0.45,
    totalGainLoss: 5400.0,
    totalGainLossPercent: 9.05,
    accounts: [
      {
        accountId: 'bullionvault-1',
        brokerId: 'bullionvault',
        brokerName: 'BullionVault',
        brokerShortName: 'BV',
        accountType: 'Vault',
        region: 'UK',
        shares: 180,
        averageCost: 331.11,
        currentValue: 65000.0,
        costBasis: 59600.0,
        gainLoss: 5400.0,
        gainLossPercent: 9.05,
        taxLots: [],
      },
    ],
  },
  {
    symbol: 'XPT',
    name: 'Platinum',
    assetClass: 'metals',
    totalShares: 12,
    totalValue: 31715.89,
    dayChange: -101.49,
    dayChangePercent: -0.32,
    totalGainLoss: 1115.89,
    totalGainLossPercent: 3.65,
    accounts: [
      {
        accountId: 'ibkr-margin-1',
        brokerId: 'ibkr',
        brokerName: 'Interactive Brokers',
        brokerShortName: 'IB',
        accountType: 'Margin',
        region: 'US',
        shares: 12,
        averageCost: 2550.0,
        currentValue: 31715.89,
        costBasis: 30600.0,
        gainLoss: 1115.89,
        gainLossPercent: 3.65,
        taxLots: [],
      },
    ],
  },
]

// Prediction Markets holdings
const predictionHoldings: PortfolioHolding[] = [
  {
    symbol: 'ELECT-2024',
    name: '2024 Presidential Election',
    assetClass: 'prediction-markets',
    totalShares: 5000,
    totalValue: 87500.0,
    dayChange: -875.0,
    dayChangePercent: -0.99,
    totalGainLoss: 12500.0,
    totalGainLossPercent: 16.67,
    accounts: [
      {
        accountId: 'polymarket-1',
        brokerId: 'polymarket',
        brokerName: 'Polymarket',
        brokerShortName: 'PM',
        accountType: 'Trading',
        region: 'Global',
        shares: 5000,
        averageCost: 15.0,
        currentValue: 87500.0,
        costBasis: 75000.0,
        gainLoss: 12500.0,
        gainLossPercent: 16.67,
        taxLots: [],
      },
    ],
  },
  {
    symbol: 'FED-RATE',
    name: 'Fed Rate Decision Mar 2025',
    assetClass: 'prediction-markets',
    totalShares: 3000,
    totalValue: 66210.4,
    dayChange: 662.1,
    dayChangePercent: 1.01,
    totalGainLoss: 6210.4,
    totalGainLossPercent: 10.35,
    accounts: [
      {
        accountId: 'kalshi-1',
        brokerId: 'kalshi',
        brokerName: 'Kalshi',
        brokerShortName: 'KA',
        accountType: 'Trading',
        region: 'US',
        shares: 3000,
        averageCost: 20.0,
        currentValue: 66210.4,
        costBasis: 60000.0,
        gainLoss: 6210.4,
        gainLossPercent: 10.35,
        taxLots: [],
      },
    ],
  },
  {
    symbol: 'BTC-100K',
    name: 'BTC Above $100K by EOY',
    assetClass: 'prediction-markets',
    totalShares: 2000,
    totalValue: 44500.0,
    dayChange: -667.5,
    dayChangePercent: -1.48,
    totalGainLoss: 4500.0,
    totalGainLossPercent: 11.25,
    accounts: [
      {
        accountId: 'polymarket-1',
        brokerId: 'polymarket',
        brokerName: 'Polymarket',
        brokerShortName: 'PM',
        accountType: 'Trading',
        region: 'Global',
        shares: 2000,
        averageCost: 20.0,
        currentValue: 44500.0,
        costBasis: 40000.0,
        gainLoss: 4500.0,
        gainLossPercent: 11.25,
        taxLots: [],
      },
    ],
  },
  {
    symbol: 'AI-GPT5',
    name: 'GPT-5 Release Q1 2025',
    assetClass: 'prediction-markets',
    totalShares: 1500,
    totalValue: 30000.0,
    dayChange: -185.3,
    dayChangePercent: -0.61,
    totalGainLoss: 3000.0,
    totalGainLossPercent: 11.11,
    accounts: [
      {
        accountId: 'kalshi-1',
        brokerId: 'kalshi',
        brokerName: 'Kalshi',
        brokerShortName: 'KA',
        accountType: 'Trading',
        region: 'US',
        shares: 1500,
        averageCost: 18.0,
        currentValue: 30000.0,
        costBasis: 27000.0,
        gainLoss: 3000.0,
        gainLossPercent: 11.11,
        taxLots: [],
      },
    ],
  },
]

// Asset Class Summaries
export const assetClassSummaries: AssetClassSummary[] = [
  {
    assetClass: 'equities',
    displayName: 'Equities',
    subtitle: 'US & International Stocks',
    icon: '📈',
    totalValue: equityHoldings.reduce((sum, h) => sum + h.totalValue, 0),
    dayChange: equityHoldings.reduce((sum, h) => sum + h.dayChange, 0),
    dayChangePercent: 1.57,
    positionCount: equityHoldings.length,
    holdings: equityHoldings,
    brokers: ['Interactive Brokers', 'Degiro', 'Saxo Bank'],
    accentColor: 'emerald',
  },
  {
    assetClass: 'fx',
    displayName: 'Foreign Exchange',
    subtitle: 'Currency positions',
    icon: '💱',
    totalValue: fxHoldings.reduce((sum, h) => sum + h.totalValue, 0),
    dayChange: fxHoldings.reduce((sum, h) => sum + h.dayChange, 0),
    dayChangePercent: 1.43,
    positionCount: fxHoldings.length,
    holdings: fxHoldings,
    brokers: ['OANDA'],
    accentColor: 'blue',
  },
  {
    assetClass: 'fixed-income',
    displayName: 'Fixed Income',
    subtitle: 'Government & Corporate',
    icon: '🏛️',
    totalValue: fixedIncomeHoldings.reduce((sum, h) => sum + h.totalValue, 0),
    dayChange: fixedIncomeHoldings.reduce((sum, h) => sum + h.dayChange, 0),
    dayChangePercent: 0.24,
    positionCount: fixedIncomeHoldings.length,
    holdings: fixedIncomeHoldings,
    brokers: ['Saxo Bank', 'Interactive Brokers'],
    accentColor: 'purple',
  },
  {
    assetClass: 'crypto',
    displayName: 'Crypto',
    subtitle: 'Digital assets',
    icon: '₿',
    totalValue: cryptoHoldings.reduce((sum, h) => sum + h.totalValue, 0),
    dayChange: cryptoHoldings.reduce((sum, h) => sum + h.dayChange, 0),
    dayChangePercent: 4.07,
    positionCount: cryptoHoldings.length,
    holdings: cryptoHoldings,
    brokers: ['Coinbase', 'Kraken'],
    accentColor: 'orange',
  },
  {
    assetClass: 'metals',
    displayName: 'Precious Metals',
    subtitle: 'Gold, Silver & Platinum',
    icon: '🥇',
    totalValue: metalsHoldings.reduce((sum, h) => sum + h.totalValue, 0),
    dayChange: metalsHoldings.reduce((sum, h) => sum + h.dayChange, 0),
    dayChangePercent: 0.64,
    positionCount: metalsHoldings.length,
    holdings: metalsHoldings,
    brokers: ['BullionVault', 'Interactive Brokers'],
    accentColor: 'gold',
  },
  {
    assetClass: 'prediction-markets',
    displayName: 'Prediction Markets',
    subtitle: 'Polymarket & Kalshi',
    icon: '🎯',
    totalValue: predictionHoldings.reduce((sum, h) => sum + h.totalValue, 0),
    dayChange: predictionHoldings.reduce((sum, h) => sum + h.dayChange, 0),
    dayChangePercent: -0.47,
    positionCount: predictionHoldings.length,
    holdings: predictionHoldings,
    brokers: ['Polymarket', 'Kalshi'],
    accentColor: 'cyan',
  },
]

// Calculate total portfolio value
const totalPortfolioValue = assetClassSummaries.reduce(
  (sum, ac) => sum + ac.totalValue,
  0
)
const totalDayChange = assetClassSummaries.reduce(
  (sum, ac) => sum + ac.dayChange,
  0
)

// Allocation segments
export const allocationSegments: AllocationSegment[] = assetClassSummaries.map(
  (ac) => ({
    assetClass: ac.assetClass,
    displayName: ac.displayName,
    percentage: Math.round((ac.totalValue / totalPortfolioValue) * 100),
    value: ac.totalValue,
    color:
      ac.accentColor === 'emerald'
        ? '#10b981'
        : ac.accentColor === 'blue'
          ? '#60a5fa'
          : ac.accentColor === 'purple'
            ? '#a78bfa'
            : ac.accentColor === 'orange'
              ? '#fb923c'
              : ac.accentColor === 'gold'
                ? '#f59e0b'
                : '#22d3ee',
  })
)

// Portfolio Summary
export const portfolioSummary: PortfolioSummary = {
  totalValue: totalPortfolioValue,
  dayChange: totalDayChange,
  dayChangePercent: (totalDayChange / (totalPortfolioValue - totalDayChange)) * 100,
  totalGainLoss: 285000.0, // Aggregate total gains
  totalGainLossPercent: 11.12,
  brokerCount: 9,
  lastSyncedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(), // 2 minutes ago
  allocation: allocationSegments,
  assetClasses: assetClassSummaries,
}

// Bento card configuration
export const bentoCardConfig: BentoCardConfig[] = [
  { assetClass: 'equities', size: 'large', order: 1 },
  { assetClass: 'crypto', size: 'tall', order: 2 },
  { assetClass: 'fx', size: 'default', order: 3 },
  { assetClass: 'fixed-income', size: 'default', order: 4 },
  { assetClass: 'metals', size: 'wide', order: 5 },
  { assetClass: 'prediction-markets', size: 'default', order: 6 },
]
