import type {
  ModelPrediction,
  ModelPerformance,
  SectorPrediction,
} from '../types/predictions'

export const modelPredictions: ModelPrediction[] = [
  {
    id: 'pred-1',
    symbol: 'NVDA',
    name: 'NVIDIA Corp.',
    sector: 'Technology',
    currentPrice: 875.28,
    predictedPrice: 945.00,
    confidence: 0.87,
    signal: 'BUY',
    timeframe: '30d',
    modelVersion: 'v3.2.1',
    lastUpdated: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    indicators: { rsi: 62.4, macd: 'bullish', trend: 'up', volatility: 0.32, momentum: 0.78, volume: 'high' },
    historicalAccuracy: 0.82,
    priceTarget: { low: 890, mid: 945, high: 1020 },
  },
  {
    id: 'pred-2',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    sector: 'Technology',
    currentPrice: 178.32,
    predictedPrice: 195.50,
    confidence: 0.79,
    signal: 'BUY',
    timeframe: '30d',
    modelVersion: 'v3.2.1',
    lastUpdated: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    indicators: { rsi: 55.8, macd: 'bullish', trend: 'up', volatility: 0.18, momentum: 0.62, volume: 'normal' },
    historicalAccuracy: 0.78,
    priceTarget: { low: 182, mid: 195.5, high: 208 },
  },
  {
    id: 'pred-3',
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    sector: 'Automotive',
    currentPrice: 248.75,
    predictedPrice: 218.00,
    confidence: 0.73,
    signal: 'SELL',
    timeframe: '30d',
    modelVersion: 'v3.2.1',
    lastUpdated: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    indicators: { rsi: 72.1, macd: 'bearish', trend: 'down', volatility: 0.45, momentum: -0.34, volume: 'high' },
    historicalAccuracy: 0.71,
    priceTarget: { low: 195, mid: 218, high: 235 },
  },
  {
    id: 'pred-4',
    symbol: 'MSFT',
    name: 'Microsoft Corp.',
    sector: 'Technology',
    currentPrice: 415.67,
    predictedPrice: 425.00,
    confidence: 0.65,
    signal: 'HOLD',
    timeframe: '30d',
    modelVersion: 'v3.2.1',
    lastUpdated: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    indicators: { rsi: 48.3, macd: 'neutral', trend: 'sideways', volatility: 0.15, momentum: 0.12, volume: 'normal' },
    historicalAccuracy: 0.76,
    priceTarget: { low: 400, mid: 425, high: 445 },
  },
  {
    id: 'pred-5',
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    sector: 'Technology',
    currentPrice: 175.42,
    predictedPrice: 192.00,
    confidence: 0.81,
    signal: 'BUY',
    timeframe: '30d',
    modelVersion: 'v3.2.1',
    lastUpdated: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    indicators: { rsi: 58.7, macd: 'bullish', trend: 'up', volatility: 0.22, momentum: 0.55, volume: 'normal' },
    historicalAccuracy: 0.79,
    priceTarget: { low: 180, mid: 192, high: 205 },
  },
  {
    id: 'pred-6',
    symbol: 'META',
    name: 'Meta Platforms',
    sector: 'Technology',
    currentPrice: 505.32,
    predictedPrice: 545.00,
    confidence: 0.76,
    signal: 'BUY',
    timeframe: '30d',
    modelVersion: 'v3.2.1',
    lastUpdated: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    indicators: { rsi: 61.2, macd: 'bullish', trend: 'up', volatility: 0.28, momentum: 0.48, volume: 'high' },
    historicalAccuracy: 0.74,
    priceTarget: { low: 515, mid: 545, high: 580 },
  },
  {
    id: 'pred-7',
    symbol: 'JPM',
    name: 'JPMorgan Chase',
    sector: 'Finance',
    currentPrice: 198.43,
    predictedPrice: 185.00,
    confidence: 0.68,
    signal: 'SELL',
    timeframe: '30d',
    modelVersion: 'v3.2.1',
    lastUpdated: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    indicators: { rsi: 68.5, macd: 'bearish', trend: 'down', volatility: 0.19, momentum: -0.22, volume: 'normal' },
    historicalAccuracy: 0.72,
    priceTarget: { low: 175, mid: 185, high: 195 },
  },
  {
    id: 'pred-8',
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    sector: 'Technology',
    currentPrice: 185.95,
    predictedPrice: 205.00,
    confidence: 0.84,
    signal: 'BUY',
    timeframe: '30d',
    modelVersion: 'v3.2.1',
    lastUpdated: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    indicators: { rsi: 54.2, macd: 'bullish', trend: 'up', volatility: 0.24, momentum: 0.65, volume: 'high' },
    historicalAccuracy: 0.81,
    priceTarget: { low: 190, mid: 205, high: 225 },
  },
  {
    id: 'pred-9',
    symbol: 'V',
    name: 'Visa Inc.',
    sector: 'Finance',
    currentPrice: 275.80,
    predictedPrice: 280.00,
    confidence: 0.58,
    signal: 'HOLD',
    timeframe: '30d',
    modelVersion: 'v3.2.1',
    lastUpdated: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    indicators: { rsi: 52.1, macd: 'neutral', trend: 'sideways', volatility: 0.12, momentum: 0.08, volume: 'low' },
    historicalAccuracy: 0.75,
    priceTarget: { low: 265, mid: 280, high: 290 },
  },
  {
    id: 'pred-10',
    symbol: 'XOM',
    name: 'Exxon Mobil',
    sector: 'Energy',
    currentPrice: 104.25,
    predictedPrice: 95.00,
    confidence: 0.71,
    signal: 'SELL',
    timeframe: '30d',
    modelVersion: 'v3.2.1',
    lastUpdated: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    indicators: { rsi: 65.8, macd: 'bearish', trend: 'down', volatility: 0.26, momentum: -0.28, volume: 'normal' },
    historicalAccuracy: 0.69,
    priceTarget: { low: 88, mid: 95, high: 100 },
  },
]

export const modelPerformance: ModelPerformance[] = [
  {
    modelId: 'lstm-v3',
    modelName: 'LSTM Ensemble',
    accuracy: 0.78,
    precision: 0.81,
    recall: 0.75,
    f1Score: 0.78,
    sharpeRatio: 1.85,
    maxDrawdown: 0.12,
    totalPredictions: 1247,
    successfulPredictions: 973,
    avgReturnOnCorrect: 0.084,
    avgLossOnIncorrect: -0.032,
  },
  {
    modelId: 'transformer-v2',
    modelName: 'Temporal Transformer',
    accuracy: 0.82,
    precision: 0.85,
    recall: 0.79,
    f1Score: 0.82,
    sharpeRatio: 2.12,
    maxDrawdown: 0.09,
    totalPredictions: 892,
    successfulPredictions: 731,
    avgReturnOnCorrect: 0.092,
    avgLossOnIncorrect: -0.028,
  },
  {
    modelId: 'xgboost-v4',
    modelName: 'XGBoost Features',
    accuracy: 0.74,
    precision: 0.76,
    recall: 0.72,
    f1Score: 0.74,
    sharpeRatio: 1.62,
    maxDrawdown: 0.15,
    totalPredictions: 1543,
    successfulPredictions: 1142,
    avgReturnOnCorrect: 0.071,
    avgLossOnIncorrect: -0.038,
  },
  {
    modelId: 'ensemble-v3',
    modelName: 'Multi-Model Ensemble',
    accuracy: 0.85,
    precision: 0.87,
    recall: 0.83,
    f1Score: 0.85,
    sharpeRatio: 2.34,
    maxDrawdown: 0.07,
    totalPredictions: 756,
    successfulPredictions: 643,
    avgReturnOnCorrect: 0.098,
    avgLossOnIncorrect: -0.025,
  },
]

export const sectorPredictions: SectorPrediction[] = [
  {
    sector: 'Technology',
    sentiment: 'bullish',
    averageConfidence: 0.79,
    buySignals: 5,
    sellSignals: 0,
    holdSignals: 1,
    topPicks: ['NVDA', 'AMZN', 'GOOGL'],
  },
  {
    sector: 'Finance',
    sentiment: 'bearish',
    averageConfidence: 0.63,
    buySignals: 0,
    sellSignals: 1,
    holdSignals: 1,
    topPicks: [],
  },
  {
    sector: 'Automotive',
    sentiment: 'bearish',
    averageConfidence: 0.73,
    buySignals: 0,
    sellSignals: 1,
    holdSignals: 0,
    topPicks: [],
  },
  {
    sector: 'Energy',
    sentiment: 'bearish',
    averageConfidence: 0.71,
    buySignals: 0,
    sellSignals: 1,
    holdSignals: 0,
    topPicks: [],
  },
  {
    sector: 'Healthcare',
    sentiment: 'neutral',
    averageConfidence: 0.62,
    buySignals: 1,
    sellSignals: 1,
    holdSignals: 2,
    topPicks: ['JNJ'],
  },
]

// Summary statistics
export const predictionSummary = {
  totalPredictions: modelPredictions.length,
  buySignals: modelPredictions.filter(p => p.signal === 'BUY').length,
  sellSignals: modelPredictions.filter(p => p.signal === 'SELL').length,
  holdSignals: modelPredictions.filter(p => p.signal === 'HOLD').length,
  averageConfidence: modelPredictions.reduce((sum, p) => sum + p.confidence, 0) / modelPredictions.length,
  highConfidencePredictions: modelPredictions.filter(p => p.confidence >= 0.75).length,
  lastModelUpdate: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  nextScheduledUpdate: new Date(Date.now() + 1000 * 60 * 45).toISOString(),
}
